[workspace]

resolver = "2"

members = [
    "sdml-cli",
    "sdml-core",
    "sdml-errors",
    "sdml-generate",
    "sdml-json",
    "sdml-parse",
    "sdml-rdf",
    "sdml-tera",
    "sdml-tests",
]
